In [1]:
import pandas as pd
df=pd.read_csv("Loan_Dataset_1000_rows-v2.csv")

In [2]:

# Missing values

df.isnull().sum()

Applicant_Name           0
Gender                   0
Loan_Purpose             0
Loan_Type                0
Annual_Income            0
Loan_Amount_Requested    0
Loan_Term                0
Credit_Score             0
Monthly_Expenses         0
Outstanding_Debt         0
Loan_Approval_Status     0
dtype: int64

In [3]:
# Duplicate rows
df.duplicated().sum()

np.int64(0)

In [4]:
# Data types
df.dtypes

Applicant_Name           object
Gender                   object
Loan_Purpose             object
Loan_Type                object
Annual_Income             int64
Loan_Amount_Requested     int64
Loan_Term                 int64
Credit_Score              int64
Monthly_Expenses          int64
Outstanding_Debt          int64
Loan_Approval_Status      int64
dtype: object

In [ ]:
# Target column
# Loan_Status

In [10]:
# Features and target
X = df.drop("Loan_Approval_Status", axis=1)
y = df["Loan_Approval_Status"]

# X = information used to make the prediction.

# y = answer the model is trying to predict.

0      1
1      0
2      0
3      0
4      0
      ..
995    0
996    1
997    0
998    0
999    0
Name: Loan_Approval_Status, Length: 1000, dtype: int64